/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UICollectionViewCell.h>

@protocol AlarmActiveDelegate;
@class AlarmView;

@interface AlarmSingleViewCollectionCell : UICollectionViewCell {

	BOOL _enabled;
	id<AlarmActiveDelegate> _alarmActiveDelegate;
	AlarmView* _alarmView;
	unsigned long long _index;

}

@property (nonatomic,readonly) AlarmView * alarmView;               //@synthesize alarmView=_alarmView - In the implementation block
@property (assign,nonatomic) unsigned long long index;              //@synthesize index=_index - In the implementation block
-(void)_alarmActiveChanged:(id)arg1 ;
-(void)refreshUI:(id)arg1 animated:(BOOL)arg2 ;
-(void)setAlarmActiveDelegate:(id)arg1 ;
-(AlarmView *)alarmView;
-(id)initWithFrame:(CGRect)arg1 ;
-(unsigned long long)index;
-(void)setIndex:(unsigned long long)arg1 ;
@end

