/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:27 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


#import <MobileTimer/MobileTimer-Structs.h>
@class NSString;

@interface AlarmScheduleLayoutData : NSObject {

	NSString* _alarmId;
	long long _hour;
	long long _minute;
	unsigned long long _daySetting;
	BOOL _active;
	BOOL _snoozed;
	NSString* _title;
	double _timePositionForItems;
	long long _daysForItems[7];
	int _cellLayoutForItems[7];

}

@property (nonatomic,retain) NSString * alarmId;                         //@synthesize alarmId=_alarmId - In the implementation block
@property (nonatomic,readonly) long long hour;                           //@synthesize hour=_hour - In the implementation block
@property (nonatomic,readonly) long long minute;                         //@synthesize minute=_minute - In the implementation block
@property (assign,nonatomic) unsigned long long daySetting;              //@synthesize daySetting=_daySetting - In the implementation block
@property (assign,getter=isActive,nonatomic) BOOL active;                //@synthesize active=_active - In the implementation block
@property (assign,getter=isSnoozed,nonatomic) BOOL snoozed;              //@synthesize snoozed=_snoozed - In the implementation block
@property (nonatomic,retain) NSString * title;                           //@synthesize title=_title - In the implementation block
+(BOOL)doesTimePosition:(double)arg1 overlapWithTimePosition:(double)arg2 overlapPercent:(double)arg3 ;
-(long long)compareToHour:(long long)arg1 minute:(long long)arg2 ;
-(long long)layout:(id)arg1 dayForItem:(long long)arg2 ;
-(long long)layout:(id)arg1 itemForDay:(long long)arg2 ;
-(long long)compareToTime:(id)arg1 ;
-(int)cellLayoutForDay:(long long)arg1 ;
-(void)setCellLayout:(int)arg1 forDay:(long long)arg2 ;
-(id)allDaysForLayout:(id)arg1 ;
-(BOOL)doesOverlapWithLayoutData:(id)arg1 fullOverlapOnly:(BOOL)arg2 ;
-(CGRect)layout:(id)arg1 frameForItem:(long long)arg2 ;
-(id)layout:(id)arg1 itemsInDayRange:(SCD_Struct_Al5)arg2 ;
-(long long)visualFirstItemWithLayout:(id)arg1 ;
-(void)setSnoozed:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(void)setTitle:(NSString *)arg1 ;
-(id)description;
-(id)debugDescription;
-(BOOL)isActive;
-(NSString *)title;
-(void)reset;
-(void)setActive:(BOOL)arg1 ;
-(long long)hour;
-(long long)minute;
-(void)setHour:(long long)arg1 minute:(long long)arg2 ;
-(void)setDaySetting:(unsigned long long)arg1 ;
-(unsigned long long)daySetting;
-(BOOL)isSnoozed;
-(NSString *)alarmId;
-(void)setAlarmId:(NSString *)arg1 ;
@end

