/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:27 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UICollectionView.h>

@class AlarmScheduleGridView, AlarmScheduleLayout;

@interface AlarmScheduleCollectionView : UICollectionView {

	AlarmScheduleGridView* _gridView;

}

@property (nonatomic,retain) AlarmScheduleLayout * collectionViewLayout; 
@property (nonatomic,retain,readonly) AlarmScheduleGridView * gridView;                  //@synthesize gridView=_gridView - In the implementation block
@property (assign,getter=isShowingNoAlarms,nonatomic) BOOL showingNoAlarms; 
-(void)setShowingNoAlarms:(BOOL)arg1 ;
-(id)frontmostVisibleCellWithAlarmBodyContainingPoint:(CGPoint)arg1 ;
-(BOOL)isShowingNoAlarms;
-(void)updateGridLayout;
-(void)dealloc;
-(void)layoutSubviews;
-(AlarmScheduleLayout *)collectionViewLayout;
-(id)initWithFrame:(CGRect)arg1 collectionViewLayout:(id)arg2 ;
-(void)setContentOffset:(CGPoint)arg1 ;
-(void)setContentSize:(CGSize)arg1 ;
-(AlarmScheduleGridView *)gridView;
@end

