/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:27 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UICollectionViewCell.h>

@class AlarmScheduleLayoutAttributes, UIView, UILabel, NSString;

@interface AlarmScheduleCollectionCell : UICollectionViewCell {

	AlarmScheduleLayoutAttributes* _attributes;
	UIView* _tileView;
	UILabel* _titleLabel;

}

@property (nonatomic,readonly) NSString * alarmId; 
+(double)height;
-(BOOL)bodyContainsPoint:(CGPoint)arg1 ;
-(void)updateColor;
-(void)updateTitleLabel;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(BOOL)pointInside:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)layoutSubviews;
-(id)description;
-(void)setSelected:(BOOL)arg1 ;
-(void)applyLayoutAttributes:(id)arg1 ;
-(NSString *)alarmId;
@end

