/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:27 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UICollectionViewLayout.h>

@class NSCalendar, NSDate, NSDateComponents, NSMutableArray, NSMutableDictionary, NSIndexPath, NSString, NSMutableSet, AlarmScheduleLayoutData, NSTimer, NSDictionary;

@interface AlarmScheduleLayout : UICollectionViewLayout {

	BOOL _needsRefreshDateInfo;
	long long _firstDayOfWeek;
	NSCalendar* _calendar;
	NSDate* _now;
	NSDateComponents* _nowComps;
	NSMutableArray* _alarmIdForSection;
	NSMutableDictionary* _layoutDataMap;
	NSMutableArray* _itemZOrder[7];
	NSMutableDictionary* _overlappingItemLists[7];
	NSIndexPath* _pendingFrontIndexPath;
	NSString* _pendingUpdatedAlarmId;
	long long _pendingUpdatedAlarmAction;
	BOOL _needsRefreshLayout;
	NSMutableSet* _changedAlarmIds;
	NSMutableSet* _pendingSnoozeChangedAlarms;
	long long _dragState;
	AlarmScheduleLayoutData* _draggingLayoutData;
	double _dragXStartLocation;
	double _dragYOffset;
	CGPoint _pendingDragLocation;
	/*^block*/id _dragCompletionBlock;
	NSTimer* _nextNonRepeatingAlarmTimer;
	NSMutableDictionary* _cachedAttributes;
	NSDictionary* _previousCachedAttributes;
	NSMutableDictionary* _cachedAttributesAlarmMap[7];
	NSMutableDictionary* _previousCachedAttributesAlarmMap[7];
	NSMutableArray* _previousAlarmIdForSection;
	NSMutableSet* _reloadedAlarms;
	NSMutableDictionary* _dayOfOverlappingReloadedAlarms;

}

@property (nonatomic,readonly) long long firstDayOfWeek;                 //@synthesize firstDayOfWeek=_firstDayOfWeek - In the implementation block
@property (nonatomic,readonly) long long currentDayOfWeek; 
@property (nonatomic,readonly) NSDate * now;                             //@synthesize now=_now - In the implementation block
@property (nonatomic,readonly) NSDateComponents * nowComps;              //@synthesize nowComps=_nowComps - In the implementation block
@property (nonatomic,readonly) double leftMargin; 
@property (nonatomic,readonly) double columnWidth; 
+(double)yForTimeInMinutes:(long long)arg1 ;
+(long long)timeInMinutesForY:(double)arg1 ;
-(void)bringAlarmToFront:(id)arg1 ;
-(BOOL)isAlarmOverlapping:(id)arg1 ;
-(id)cycleAlarmToBack:(id)arg1 ;
-(void)beginDraggingAlarmId:(id)arg1 fromLocationInSuperview:(CGPoint)arg2 ;
-(void)dragAlarmToLocationInSuperview:(CGPoint)arg1 completion:(/*^block*/id)arg2 ;
-(void)endDraggingAlarmWithInvalidation:(BOOL)arg1 ;
-(void)setPendingUpdatedAlarmId:(id)arg1 action:(long long)arg2 ;
-(void)addPendingSnoozeChangedForAlarmId:(id)arg1 ;
-(void)setNeedsRefreshLayoutWithChangedAlarmIds:(id)arg1 ;
-(long long)currentDayOfWeek;
-(void)setNeedsRefreshDateInfo;
-(NSDateComponents *)nowComps;
-(BOOL)refreshDateInfo;
-(void)setNeedsRefreshDateInfoWithInvalidation:(BOOL)arg1 ;
-(void)resetEverything;
-(void)handleNextNonRepeatingAlarm;
-(id)fullyOverlappingAlarmsForAlarm:(id)arg1 forDay:(long long)arg2 ;
-(void)resetAllAlarmLayout;
-(void)resetAllAlarmOperations;
-(void)calculateLayoutForAllAlarms;
-(void)handleReloadOfAlarm:(id)arg1 ;
-(void)handleInsertOfAlarm:(id)arg1 ;
-(void)handleDeleteOfAlarm:(id)arg1 ;
-(long long)columnIndexForX:(double)arg1 ;
-(void)handleDeleteOfAlarm:(id)arg1 forDays:(id)arg2 ;
-(void)handleInsertOfAlarm:(id)arg1 atZIndex:(long long)arg2 forDays:(id)arg3 ;
-(void)scheduleTimerForNextNonRepeatingAlarm;
-(void)determineOverlappingItemListsForAlarms:(id)arg1 onDay:(long long)arg2 ;
-(id)sortLayoutDataByTime:(id)arg1 forDay:(long long)arg2 ;
-(void)handleNoLongerOverlappingAlarm:(id)arg1 forDay:(long long)arg2 ;
-(SCD_Struct_Al5)daysVisibleInRect:(CGRect)arg1 ;
-(SCD_Struct_Al6)timesVisibleInRect:(CGRect)arg1 ;
-(NSDate *)now;
-(void)dealloc;
-(id)init;
-(id)layoutAttributesForElementsInRect:(CGRect)arg1 ;
-(id)layoutAttributesForItemAtIndexPath:(id)arg1 ;
-(CGSize)collectionViewContentSize;
-(void)prepareLayout;
-(double)rightMargin;
-(double)columnWidth;
-(BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)arg1 ;
-(id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1 ;
-(id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1 ;
-(void)prepareForCollectionViewUpdates:(id)arg1 ;
-(void)finalizeCollectionViewUpdates;
-(long long)firstDayOfWeek;
-(double)leftMargin;
@end

