/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:27 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@class AlarmScheduleHeaderView, AlarmScheduleCollectionView;

@interface AlarmScheduleView : UIView {

	AlarmScheduleHeaderView* _headerView;
	AlarmScheduleCollectionView* _alarmsView;
	long long _currentDay;

}

@property (nonatomic,readonly) AlarmScheduleHeaderView * headerView;                  //@synthesize headerView=_headerView - In the implementation block
@property (nonatomic,readonly) AlarmScheduleCollectionView * alarmsView;              //@synthesize alarmsView=_alarmsView - In the implementation block
@property (assign,nonatomic) long long currentDay;                                    //@synthesize currentDay=_currentDay - In the implementation block
-(void)handleLocaleChange;
-(AlarmScheduleCollectionView *)alarmsView;
-(void)refreshHeader;
-(void)handleSignificantTimeChange;
-(long long)currentDay;
-(void)setCurrentDay:(long long)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(AlarmScheduleHeaderView *)headerView;
@end

