/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@protocol AlarmActiveDelegate;
@class AlarmView;

@interface AlarmTableViewCell : UITableViewCell {

	id<AlarmActiveDelegate> _alarmActiveDelegate;
	AlarmView* _alarmView;
	BOOL _enabled;

}
+(double)defaultHeight;
-(void)_alarmActiveChanged:(id)arg1 ;
-(void)refreshUI:(id)arg1 animated:(BOOL)arg2 ;
-(void)setAlarmActiveDelegate:(id)arg1 ;
-(void)internalSetBackgroundColor:(id)arg1 ;
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(void)setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setSelected:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)willTransitionToState:(unsigned long long)arg1 ;
@end

