/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UICollectionViewLayoutAttributes.h>

@interface ChunkedGridLayoutAttributes : UICollectionViewLayoutAttributes {

	unsigned long long _gridPosition;

}

@property (assign,nonatomic) unsigned long long gridPosition;              //@synthesize gridPosition=_gridPosition - In the implementation block
-(unsigned long long)gridPosition;
-(void)setGridPosition:(unsigned long long)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(id)description;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

