/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:27 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@class UIColor;

@interface CircleProgressView : UIView {

	double _progress;
	double _animateNextPathChange;
	UIColor* _color;
	double _thickness;

}

@property (assign,nonatomic) double progress;                           //@synthesize progress=_progress - In the implementation block
@property (assign,nonatomic) double animateNextPathChange;              //@synthesize animateNextPathChange=_animateNextPathChange - In the implementation block
@property (nonatomic,retain) UIColor * color;                           //@synthesize color=_color - In the implementation block
@property (assign,nonatomic) double thickness;                          //@synthesize thickness=_thickness - In the implementation block
-(void)setAnimateNextPathChange:(double)arg1 ;
-(double)animateNextPathChange;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)drawRect:(CGRect)arg1 ;
-(void)setProgress:(double)arg1 ;
-(UIColor *)color;
-(void)setColor:(UIColor *)arg1 ;
-(double)progress;
-(void)setThickness:(double)arg1 ;
-(double)thickness;
@end

