/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIViewController.h>
#import <MobileTimer/FullScreenWorldClockCollectionCellDelegate.h>
#import <UIKit/UICollectionViewDataSource.h>
#import <UIKit/UICollectionViewDelegate.h>
#import <UIKit/UICollectionViewDelegateFlowLayout.h>

@class NSTimer, UIPinchGestureRecognizer, FullScreenWorldClockCollectionCell, UIPageControl, UIButton, UICollectionView, NSString;

@interface FullScreenWorldClockCollectionController : UIViewController <FullScreenWorldClockCollectionCellDelegate, UICollectionViewDataSource, UICollectionViewDelegate, UICollectionViewDelegateFlowLayout> {

	NSTimer* _hideInfoTimer;
	BOOL _showingInfo;
	BOOL _showingInfoTemporarily;
	id _dismissTarget;
	SEL _dismissAction;
	long long _currentPage;
	UIPinchGestureRecognizer* _pinchGestureRecognizer;
	FullScreenWorldClockCollectionCell* _transitionView;
	BOOL _shouldHideInfoAfterScroll;
	int _clockAppearance;
	UIPageControl* _pageIndicator;
	UIButton* _twcButton;
	UICollectionView* _collectionView;

}

@property (nonatomic,readonly) UIPageControl * pageIndicator;                         //@synthesize pageIndicator=_pageIndicator - In the implementation block
@property (nonatomic,readonly) UIButton * twcButton;                                  //@synthesize twcButton=_twcButton - In the implementation block
@property (nonatomic,retain,readonly) UICollectionView * collectionView;              //@synthesize collectionView=_collectionView - In the implementation block
@property (assign,nonatomic) int clockAppearance;                                     //@synthesize clockAppearance=_clockAppearance - In the implementation block
@property (assign,nonatomic) BOOL shouldHideInfoAfterScroll;                          //@synthesize shouldHideInfoAfterScroll=_shouldHideInfoAfterScroll - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)scrollToCurrentPage;
-(UIPageControl *)pageIndicator;
-(void)weatherDataUpdated;
-(void)setDismissTarget:(id)arg1 action:(SEL)arg2 ;
-(void)setClockAppearance:(int)arg1 ;
-(void)pinchAction:(id)arg1 ;
-(void)handleApplicationDidEnterBackground;
-(void)handleApplicationWillEnterForeground;
-(void)updatePageIndicator;
-(UIButton *)twcButton;
-(void)hideInfoAfterDelay;
-(void)cancelDelayedHideInfo;
-(BOOL)isCurrentPageNighttime;
-(void)twcButtonPressed;
-(void)setShowingInfo:(BOOL)arg1 forCell:(id)arg2 ;
-(void)setShowingInfo:(BOOL)arg1 ;
-(void)hideInfo;
-(void)updatePageIndicatorColor:(BOOL)arg1 ;
-(void)configureFullScreenWorldClockCollectionCell:(id)arg1 indexPath:(id)arg2 ;
-(void)hideInfoIfTemporarilyShowing;
-(void)cellBackgroundDidUpdate:(id)arg1 isDayTime:(BOOL)arg2 ;
-(int)clockAppearance;
-(BOOL)shouldHideInfoAfterScroll;
-(void)setShouldHideInfoAfterScroll:(BOOL)arg1 ;
-(void)dealloc;
-(id)init;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(void)scrollViewDidEndScrollingAnimation:(id)arg1 ;
-(long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2 ;
-(void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3 ;
-(UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3 ;
-(double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3 ;
-(double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3 ;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(UICollectionView *)collectionView;
-(void)loadView;
-(CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)dismiss;
-(CGPoint)_collectionView:(id)arg1 targetContentOffsetForProposedContentOffset:(CGPoint)arg2 ;
@end

