/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UICollectionViewCell.h>
#import <MobileTimer/WorldClockViewBackgroundHost.h>

@protocol FullScreenWorldClockCollectionCellDelegate;
@class UIView, WorldClockView, NSString;

@interface FullScreenWorldClockCollectionCell : UICollectionViewCell <WorldClockViewBackgroundHost> {

	UIView* _clockBackground;
	WorldClockView* _clockView;
	id<FullScreenWorldClockCollectionCellDelegate> _delegate;

}

@property (nonatomic,readonly) UIView * clockBackground;                                           //@synthesize clockBackground=_clockBackground - In the implementation block
@property (nonatomic,readonly) WorldClockView * clockView;                                         //@synthesize clockView=_clockView - In the implementation block
@property (assign,nonatomic) id<FullScreenWorldClockCollectionCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)dayTimeBackgroundColor;
+(id)nightTimeBackgroundColor;
-(WorldClockView *)clockView;
-(UIView *)clockBackground;
-(void)updateBackground:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id<FullScreenWorldClockCollectionCellDelegate>)arg1 ;
-(void)layoutSubviews;
-(id<FullScreenWorldClockCollectionCellDelegate>)delegate;
@end

