/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>
#import <MobileTimer/StopWatchLapCell.h>

@class UILabel, UIView, NSString;

@interface LapPadTableViewCell : UITableViewCell <StopWatchLapCell> {

	int _lap;
	double _time;
	double _runningTotal;
	UILabel* _lapLabel;
	UILabel* _runningTotalLabel;
	UILabel* _timeLabel;
	UIView* _keylineView;
	int _cellPosition;

}

@property (assign,nonatomic) int lap;                               //@synthesize lap=_lap - In the implementation block
@property (assign,nonatomic) double time;                           //@synthesize time=_time - In the implementation block
@property (assign,nonatomic) double runningTotal;                   //@synthesize runningTotal=_runningTotal - In the implementation block
@property (assign,nonatomic) int cellPosition;                      //@synthesize cellPosition=_cellPosition - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(double)rightLabelCenterXToTrailing;
+(double)leftLabelCenterXToLeading;
+(double)rowHeight;
-(void)handleLocaleChange;
-(void)setLap:(int)arg1 ;
-(void)setRunningTotal:(double)arg1 ;
-(void)internalSetBackgroundColor:(id)arg1 ;
-(void)setupLapFormatter;
-(void)resetLapFormatter;
-(id)_accessibilityFormatTime:(double)arg1 showHours:(BOOL*)arg2 showSubseconds:(BOOL)arg3 ;
-(int)lap;
-(double)runningTotal;
-(void)setCellPosition:(int)arg1 ;
-(int)cellPosition;
-(void)dealloc;
-(void)setBackgroundColor:(id)arg1 ;
-(id)init;
-(void)layoutSubviews;
-(void)prepareForReuse;
-(void)setTime:(double)arg1 ;
-(double)time;
@end

