/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UICollectionViewCell.h>

@class WorldClockMapView;

@interface MapCollectionCell : UICollectionViewCell {

	WorldClockMapView* _mapView;
	UIEdgeInsets _padding;

}

@property (nonatomic,retain,readonly) WorldClockMapView * mapView;              //@synthesize mapView=_mapView - In the implementation block
@property (assign,nonatomic) UIEdgeInsets padding;                              //@synthesize padding=_padding - In the implementation block
-(WorldClockMapView *)mapView;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setPadding:(UIEdgeInsets)arg1 ;
-(UIEdgeInsets)padding;
@end

