/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UITabBarController.h>

@class UINavigationController;

@interface MobileTimerTabBarController : UITabBarController {

	UINavigationController* _stopwatchNavController;
	UINavigationController* _timerNavController;
	UINavigationController* _alarmNavControllerSmall;
	UINavigationController* _alarmNavController;
	UINavigationController* _worldClockNavControllerSmall;
	UINavigationController* _worldClockNavController;

}
-(id)worldClockViewController;
-(id)alarmViewController;
-(id)stopwatchViewController;
-(id)timerViewController;
-(void)invalidateViewControllers;
-(id)navigationControllerForHorizontalSizeClass:(long long)arg1 verticalSizeClass:(long long)arg2 atIndex:(unsigned long long)arg3 ;
-(id)topViewControllerForTab:(int)arg1 ;
-(void)dealloc;
-(unsigned long long)supportedInterfaceOrientations;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
@end

