/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIButton.h>

@interface MTCircleButton : UIButton {

	unsigned long long _buttonCircleSize;

}

@property (assign,nonatomic) unsigned long long buttonCircleSize;              //@synthesize buttonCircleSize=_buttonCircleSize - In the implementation block
-(void)setColor:(unsigned long long)arg1 forState:(unsigned long long)arg2 ;
-(void)setButtonCircleSize:(unsigned long long)arg1 ;
-(unsigned long long)buttonCircleSize;
-(id)initWithFrame:(CGRect)arg1 ;
@end

