/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol TimerControlsTarget;
@class MTCircleButton;

@interface MTTimerButtonsController : NSObject {

	int _state;
	id<TimerControlsTarget> _target;
	MTCircleButton* _leftButton;
	MTCircleButton* _rightButton;
	unsigned long long _buttonSize;

}

@property (nonatomic,readonly) id<TimerControlsTarget> target;                   //@synthesize target=_target - In the implementation block
@property (nonatomic,retain,readonly) MTCircleButton * leftButton;               //@synthesize leftButton=_leftButton - In the implementation block
@property (nonatomic,retain,readonly) MTCircleButton * rightButton;              //@synthesize rightButton=_rightButton - In the implementation block
@property (assign,nonatomic) int state;                                          //@synthesize state=_state - In the implementation block
@property (assign,nonatomic) unsigned long long buttonSize;                      //@synthesize buttonSize=_buttonSize - In the implementation block
-(void)_leftButtonTapped:(id)arg1 ;
-(void)_rightButtonTapped:(id)arg1 ;
-(void)setButtonSize:(unsigned long long)arg1 ;
-(unsigned long long)buttonSize;
-(void)dealloc;
-(int)state;
-(void)setState:(int)arg1 ;
-(id<TimerControlsTarget>)target;
-(id)initWithTarget:(id)arg1 ;
-(MTCircleButton *)leftButton;
-(MTCircleButton *)rightButton;
@end

