/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <MobileTimer/TableViewController.h>
#import <UIKit/UICollectionViewDataSource.h>
#import <UIKit/UICollectionViewDelegate.h>

@class UICollectionView, UIPageControl, NSIndexPath, NSString;

@interface PagingLandscapeCollectionViewController : TableViewController <UICollectionViewDataSource, UICollectionViewDelegate> {

	BOOL _showPagingCollectionView;
	UICollectionView* _pagingCollectionView;
	UIPageControl* _pageIndicator;
	NSIndexPath* _collectionViewIndexPathBeforeRotation;
	long long _currentPage;

}

@property (nonatomic,readonly) UICollectionView * pagingCollectionView;              //@synthesize pagingCollectionView=_pagingCollectionView - In the implementation block
@property (nonatomic,readonly) long long currentPage;                                //@synthesize currentPage=_currentPage - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)scrollToCurrentPage;
-(void)pagingCollectionViewDidLoad;
-(UICollectionView *)pagingCollectionView;
-(CGSize)landscapeCellSize;
-(void)pagingCollectionViewDidAppear;
-(void)pagingCollectionViewDidDisappear;
-(id)pagingCollectionViewRotationBackgroundColor;
-(BOOL)shouldShowPagingCollectionView;
-(void)updateShowPagingCollectionView;
-(void)updatePageIndicator;
-(void)setShowPagingCollectionView:(BOOL)arg1 ;
-(void)loadPagingCollectionView;
-(BOOL)canShowPagingCollectionView;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2 ;
-(id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2 ;
-(UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3 ;
-(double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3 ;
-(double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3 ;
-(BOOL)prefersStatusBarHidden;
-(void)viewDidLayoutSubviews;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidUnload;
-(long long)currentPage;
-(void)reloadState;
@end

