/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIViewController.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>
#import <MobileTimer/StateManagement.h>
#import <MobileTimer/StopWatchControlsTarget.h>

@class MTStopwatchControlsView, StopwatchPadControls, UITableView, CADisplayLink, NSDate, NSMutableArray, NSTimer, NSString;

@interface StopWatchViewController : UIViewController <UITableViewDelegate, UITableViewDataSource, StateManagement, StopWatchControlsTarget> {

	MTStopwatchControlsView* _lapControls;
	StopwatchPadControls* _padControls;
	UITableView* _lapTimeTable;
	CADisplayLink* _displayLink;
	NSDate* _startTime;
	double _offset;
	double _currentInterval;
	double _previousLapsTotalInterval;
	NSMutableArray* _laps;
	BOOL _isTimerRunning;
	NSTimer* _restoreIdleTimerTimer;
	int _mode;
	int _style;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)handleLocaleChange;
-(void)_restoreIdleTimer;
-(void)_clearAllLaps;
-(void)_addLap:(double)arg1 ;
-(double)_timeAdjustedFor30fpsDisplay:(double)arg1 ;
-(unsigned long long)_placeholderCellCount;
-(double)runningTotalForLap:(long long)arg1 ;
-(void)startLapTimer;
-(void)resumeLapTimer;
-(void)pauseLapTimer;
-(void)lapLapTimer;
-(void)resetLapTimer;
-(void)_tick:(id)arg1 ;
-(void)saveState;
-(void)dealloc;
-(id)init;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(BOOL)prefersStatusBarHidden;
-(void)traitCollectionDidChange:(id)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)setStyle:(int)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)loadView;
-(void)viewDidUnload;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(id)defaultPNGName;
-(void)setMode:(int)arg1 ;
-(void)_startTimer;
-(void)_stopTimer;
-(void)reloadState;
-(Class)tableCellClass;
@end

