/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <MobileTimer/TimeView.h>

@class UILabel;

@interface StopwatchTimeView : TimeView {

	double _currentLapTimeInterval;
	UILabel* _currentLapTimeLabel;
	long long _style;

}

@property (assign,nonatomic) double currentLapTime;              //@synthesize currentLapTimeInterval=_currentLapTimeInterval - In the implementation block
@property (assign,nonatomic) long long style;                    //@synthesize style=_style - In the implementation block
+(double)defaultHeight;
-(void)handleLocaleChange;
-(void)setCurrentLapTime:(double)arg1 ;
-(void)configureTimeLabel;
-(void)configureBackground;
-(BOOL)showSubseconds;
-(void)_updateCurrentLapTime;
-(void)_layoutWithSize:(CGSize)arg1 maxY:(double*)arg2 ;
-(double)currentLapTime;
-(void)dealloc;
-(id)init;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(long long)style;
-(void)setStyle:(long long)arg1 ;
@end

