/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@class UILabel;

@interface TimeView : UIView {

	double _timeValue;
	UILabel* _timeLabel;
	double _maxTimeLabelWidth;

}

@property (assign,nonatomic) double time; 
@property (nonatomic,readonly) UILabel * timeLabel;              //@synthesize timeLabel=_timeLabel - In the implementation block
+(double)defaultHeight;
-(void)handleLocaleChange;
-(void)configureTimeLabel;
-(void)sizeLabelToFit;
-(void)configureBackground;
-(BOOL)showSubseconds;
-(void)setTimeLabelFrame:(CGRect)arg1 ;
-(void)dealloc;
-(id)init;
-(void)layoutSubviews;
-(void)setTime:(double)arg1 ;
-(double)time;
-(UILabel *)timeLabel;
@end

