/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/


@protocol TKTonePickerViewControllerDelegate <NSObject>
@optional
-(void)tonePickerViewController:(id)arg1 selectedToneWithIdentifier:(id)arg2;
-(void)tonePickerViewController:(id)arg1 selectedMediaItemWithIdentifier:(id)arg2;
-(void)tonePickerViewController:(id)arg1 willPresentVibrationPickerViewController:(id)arg2;
-(void)tonePickerViewController:(id)arg1 didDismissVibrationPickerViewController:(id)arg2;

@end

