/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:27 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@protocol WorldClockCollectionEditDelegate;
@class UIButton;

@interface WeatherAttributionView : UIView {

	id<WorldClockCollectionEditDelegate> _delegate;
	UIButton* _twcButton;

}

@property (assign,nonatomic) id<WorldClockCollectionEditDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) UIButton * twcButton;                                       //@synthesize twcButton=_twcButton - In the implementation block
-(UIButton *)twcButton;
-(void)_twcLogoTapped;
-(void)setTwcButton:(UIButton *)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)setDelegate:(id<WorldClockCollectionEditDelegate>)arg1 ;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<WorldClockCollectionEditDelegate>)delegate;
@end

