/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@class WorldClockCity;

@interface WorldClockCollectionEditCell : UITableViewCell {

	WorldClockCity* _city;

}

@property (nonatomic,retain) WorldClockCity * city;              //@synthesize city=_city - In the implementation block
-(WorldClockCity *)city;
-(void)setCity:(WorldClockCity *)arg1 ;
-(void)dealloc;
-(id)init;
@end

