/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIPageControl.h>

@class UIImage;

@interface WorldClockPageControl : UIPageControl {

	UIImage* _indicator;
	UIImage* _currentIndicator;

}
-(id)initWithFrame:(CGRect)arg1 useNeutralColor:(BOOL)arg2 ;
-(void)dealloc;
-(id)_pageIndicatorImageForPage:(long long)arg1 ;
-(id)_pageIndicatorCurrentImageForPage:(long long)arg1 ;
@end

