/*
* This header is generated by classdump-dyld 0.7
* on Friday, July 10, 2015 at 1:06:26 PM Central European Summer Time
* Operating System: Version 8.4 (Build 12H143)
* Image Source: /var/db/stash/_.4xjUVk/Applications/MobileTimer.app/MobileTimer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2014 by Elias Limneos.
*/

#import <MobileTimer/MobileTimer-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableDictionary, WorldClockMapCityView, NSDateFormatter, UIImageView, UIImage, NSDate, NSTimer, UIButton;

@interface WorldClockMapView : UIView {

	NSMutableDictionary* _cityViews;
	WorldClockMapCityView* _addedCityView;
	NSDateFormatter* _timeFormatter;
	double _maxTimeStringWidth;
	double _maxTemperatureStringWidth;
	UIImageView* _mapWithTerminator;
	UIImage* _terminatorImages[2];
	NSDate* _terminatorTimestamp;
	NSTimer* _terminatorTimer;
	UIButton* _twcButton;

}
+(void)updateNewYearsDay;
-(void)handleLocaleChange;
-(void)weatherDataUpdatedForCities:(id)arg1 ;
-(void)startUpdatingTime;
-(void)stopUpdatingTime;
-(void)updateTerminator;
-(double)maxWidthForDateStringWithFont:(id)arg1 ;
-(double)maxWidthForTemperatureStringWithFont:(id)arg1 ;
-(void)addCity:(id)arg1 animated:(BOOL)arg2 ;
-(void)twcButtonPressed;
-(void)handleSignificantTimeChange:(id)arg1 ;
-(void)scheduleTerminatorUpdate;
-(void)cancelTerminatorUpdate;
-(double)terminatorUpdateInterval;
-(id)terminatorPathForDayOfYear:(double)arg1 orientation:(long long)arg2 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)dealloc;
-(void)layoutSubviews;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(void)viewWillTransitionToSize:(CGSize)arg1 withTransitionCoordinator:(id)arg2 ;
-(void)addCity:(id)arg1 ;
-(void)removeCity:(id)arg1 ;
@end

